name: Website CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - main
    paths:
      - 'sports-platform/website/**'
      - '.github/workflows/website-pipeline.yml'
      - '.github/workflows/deploy-website.yml'

permissions:
  id-token: write
  contents: read

jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/deploy-website.yml
    with:
      environment: staging
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      S3_BUCKET: ${{ secrets.S3_BUCKET_STAGING }}
      API_URL: ${{ secrets.API_URL_STAGING }}

  deploy-production:
    needs: deploy-staging
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-website.yml
    with:
      environment: production
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      S3_BUCKET: ${{ secrets.S3_BUCKET_PRODUCTION }}
      API_URL: ${{ secrets.API_URL_PRODUCTION }}
