name: Website CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - main
    paths:
      - 'sports-platform/website/**'
      - '.github/workflows/website-pipeline.yml'
      - '.github/workflows/deployment.yml'

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/deployment.yml
    with:
      environment: staging
      deploy-type: website
    secrets:
      S3_BUCKET: ${{ secrets.S3_BUCKET_STAGING }}
      API_URL: ${{ secrets.API_URL_STAGING }}

  deploy-production:
    needs: deploy-staging
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deployment.yml
    with:
      environment: production
      deploy-type: website
    secrets:
      S3_BUCKET: ${{ secrets.S3_BUCKET_PRODUCTION }}
      API_URL: ${{ secrets.API_URL_PRODUCTION }}